### ISSUE TITLE
Morfismo identità nella categoria per TypeScript

### ISSUE THREAD

**Issue by gmlion** [gcanti/functional-programming#31]
Date le premesse della categoria TS:
- gli oggetti sono tutti i tipi di TypeScript
- i morfismi sono tutte le funzioni di TypeScript
non ne dovrebbe conseguire che i morfismi identità sono tutte le funzioni (a: 'T) => 'T, anziché la sola funzione identità? Ad esempio, la funzione double rispetta i requisiti del morfismo identità.

**Comment by gmlion** [comment]
Probabilmente l'ambiguità alla base di tutto sta nella definizione di uguaglianza fra morfismi, dal momento che nel modello non c'è il concetto di valore di dominio.

**Comment by gmlion** [comment]
A ben pensare la stessa obiezione si potrebbe muovere anche nei confronti della composizione, quindi ne deduco che siano scelte da considerare parte della definizione di quella particolare categoria.

**Comment by gcanti** [comment]
> Ad esempio, la funzione double rispetta i requisiti del morfismo identità.

@gmlion `double` non è né identità a destra né identità a sinistra, riporto qui sotto i requisiti richiesti:

(**identity**) per ogni oggetto `X`, esiste un morfismo `idX: X ⟼ X` chiamato *il morfismo identità* di `X`, tale che per ogni morfismo `f: A ⟼ X` e ogni morfismo `g: X ⟼ B`, vale `idX ∘ f = f` e `g ∘ idX = g`.

**Comment by gmlion** [comment]
L'oggetto X in questo caso non è un tipo? Per cui idInt: int ⟼ int

**Comment by gcanti** [comment]
Ti riporto un controesempio: nei requisiti per il morfismo identità espressi nel mio commento sopra prendiamo `X = number` e `f = (s: string): number => s.length`, non è vero che: 

`double ∘ f = f`

quindi `double` non può essere preso come morfismo identità

**Comment by gmlion** [comment]
Come dicevo sopra, tutto mi sembra dipenda da come è definita l'uguaglianza nella categoria, perché se essa è fra gli oggetti della categoria (ovvero i tipi) la leggo soddisfatta.
In questa interpretazione,
``double ∘ f``  e ``f`` sono morfismi dall'oggetto string all'oggetto number, quindi nella categoria dei tipi "uguali".

**Comment by gmlion** [comment]
Da ulteriori ricerche mi pare di capire che le "identità" di cui parlo sono in verità endomorfismi, per cui dall'uguaglianza fra oggetti non si deduce l'uguaglianza fra i morfismi. La seconda, quindi, viene "presa in prestito" dal contesto a cui la categoria fa riferimento, ovvero le funzioni di TS.
