### ISSUE TITLE
Possibile errore lift monadi

### ISSUE THREAD

**Issue by GiBg1aN** [gcanti/functional-programming#6]
Nella sezione riguardante le monadi forse hai dimenticato una "F", nello specifico, nel punto:

"E' possibile applicare un lifting a f ottenendo F[f]: F[B] -> F[F[C]]. Ora F[f] e g compongono in un morfismo A -> F[[C]] ma qui rimango bloccato."

Immagino che "A->F[[C]]" dovesse essere "A->F[F[C]]"

**Comment by gcanti** [comment]
Corretto, grazie!
